language: go
go:
- 1.15
services: mongodb
install:
- set -e ; for module in $(ls -d */) ; do dir=$(basename $module) ; echo "\n==========\nInstalling deps for $dir\n==========\n" ; cd $dir ; go get -v ./... ;  cd .. ; done
script:
- set -e ; for module in $(ls -d */) ; do dir=$(basename $module) ; echo "\n==========\nTesting $dir\n==========\n" ; cd $dir ; go test -v ./... ; cd .. ; done
notifications:
  slack:
    secure: Y9bS4jIKNXLM+pCt06gXiG0QMK0iqxU5WVxnLYCs1Eq4oLLDsAqQv79IYEDZ3tZ3YSF7IR2JaVrVidA6k+DHhHnv72kojSWEtUZNJ3SD3OYk+I5cpE11poxMAZupnHK8oytlV5e0WRqQH3A5zIk6ylwQpo/hOcsNdODh8K6fErgCikpQMKztwWRDZl0FlD0eaF4xTst2FatldoO67fYuzkK0F4OgHMlpH7RKixCdfZwAgp6L1a5BNmFfcCMDccuCTi9GB2fo3Oigs3t3uliuIg8DUKYJAO21bYs0doff+nhqmg+ClZPfebXSP/lhQ0oMlqNyDSv+4LjySXYQNI5VjPvmz3oFJBiOgLTo2FKSxtbY4kCVh8UaJFPxjteqpoaAMHAvyoYQApUqfoOM8HxdzrKmQ8S1hISoIdem2p6M0V9JZD92w3yOapeZ5DYt4MT+iYINGbzaqRr4n5n0DCcVwqebPVnXS+Gbuiu6LcVVZvoK8UIni1/AZ5aXFvmulEFKkfnDxU2ySvWDNmxMgCWRieRiSIJcsauFwlkEARvfMjHBUt15zgqaKevsn3GUcfUuYVd0Qr1aNGa0w8qDWz2L02YnEkEtmiigaxZ14GLJkOnTVvC/8SnrnbrnOfcQ11U0ShLmwcS4FgwdSt6dISMEzHe8CXYDM4QAbpYyjsX1LjI=
