// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/appsdeck-database/controller/backup/storage/s3 (interfaces: S3Client)

// Package s3mock is a generated GoMock package.
package s3mock

import (
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "github.com/golang/mock/gomock"
)

// MockS3Client is a mock of S3Client interface
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// DeleteObjectRequest mocks base method
func (m *MockS3Client) DeleteObjectRequest(arg0 *s3.DeleteObjectInput) s3.DeleteObjectRequest {
	ret := m.ctrl.Call(m, "DeleteObjectRequest", arg0)
	ret0, _ := ret[0].(s3.DeleteObjectRequest)
	return ret0
}

// DeleteObjectRequest indicates an expected call of DeleteObjectRequest
func (mr *MockS3ClientMockRecorder) DeleteObjectRequest(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectRequest", reflect.TypeOf((*MockS3Client)(nil).DeleteObjectRequest), arg0)
}

// GetObjectRequest mocks base method
func (m *MockS3Client) GetObjectRequest(arg0 *s3.GetObjectInput) s3.GetObjectRequest {
	ret := m.ctrl.Call(m, "GetObjectRequest", arg0)
	ret0, _ := ret[0].(s3.GetObjectRequest)
	return ret0
}

// GetObjectRequest indicates an expected call of GetObjectRequest
func (mr *MockS3ClientMockRecorder) GetObjectRequest(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectRequest", reflect.TypeOf((*MockS3Client)(nil).GetObjectRequest), arg0)
}

// HeadObjectRequest mocks base method
func (m *MockS3Client) HeadObjectRequest(arg0 *s3.HeadObjectInput) s3.HeadObjectRequest {
	ret := m.ctrl.Call(m, "HeadObjectRequest", arg0)
	ret0, _ := ret[0].(s3.HeadObjectRequest)
	return ret0
}

// HeadObjectRequest indicates an expected call of HeadObjectRequest
func (mr *MockS3ClientMockRecorder) HeadObjectRequest(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadObjectRequest", reflect.TypeOf((*MockS3Client)(nil).HeadObjectRequest), arg0)
}
