// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/go-utils/nsqlbproducer (interfaces: PublishPinger)

// Package nsqlbproducermock is a generated GoMock package.
package nsqlbproducermock

import (
	context "context"
	nsqproducer "github.com/Scalingo/go-utils/nsqproducer"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPublishPinger is a mock of PublishPinger interface
type MockPublishPinger struct {
	ctrl     *gomock.Controller
	recorder *MockPublishPingerMockRecorder
}

// MockPublishPingerMockRecorder is the mock recorder for MockPublishPinger
type MockPublishPingerMockRecorder struct {
	mock *MockPublishPinger
}

// NewMockPublishPinger creates a new mock instance
func NewMockPublishPinger(ctrl *gomock.Controller) *MockPublishPinger {
	mock := &MockPublishPinger{ctrl: ctrl}
	mock.recorder = &MockPublishPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPublishPinger) EXPECT() *MockPublishPingerMockRecorder {
	return m.recorder
}

// DeferredPublish mocks base method
func (m *MockPublishPinger) DeferredPublish(arg0 context.Context, arg1 string, arg2 int64, arg3 nsqproducer.NsqMessageSerialize) error {
	ret := m.ctrl.Call(m, "DeferredPublish", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeferredPublish indicates an expected call of DeferredPublish
func (mr *MockPublishPingerMockRecorder) DeferredPublish(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeferredPublish", reflect.TypeOf((*MockPublishPinger)(nil).DeferredPublish), arg0, arg1, arg2, arg3)
}

// Ping mocks base method
func (m *MockPublishPinger) Ping() error {
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping
func (mr *MockPublishPingerMockRecorder) Ping() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPublishPinger)(nil).Ping))
}

// Publish mocks base method
func (m *MockPublishPinger) Publish(arg0 context.Context, arg1 string, arg2 nsqproducer.NsqMessageSerialize) error {
	ret := m.ctrl.Call(m, "Publish", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockPublishPingerMockRecorder) Publish(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublishPinger)(nil).Publish), arg0, arg1, arg2)
}

// Stop mocks base method
func (m *MockPublishPinger) Stop() {
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop
func (mr *MockPublishPingerMockRecorder) Stop() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPublishPinger)(nil).Stop))
}
