// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Int64ObservableCounter)

// Package otelmock is a generated GoMock package.
package otelmock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"go.opentelemetry.io/otel/metric"
)

// MockInt64ObservableCounter is a mock of Int64ObservableCounter interface.
type MockInt64ObservableCounter struct {
	metric.Int64ObservableCounter

	ctrl     *gomock.Controller
	recorder *MockInt64ObservableCounterMockRecorder
}

// MockInt64ObservableCounterMockRecorder is the mock recorder for MockInt64ObservableCounter.
type MockInt64ObservableCounterMockRecorder struct {
	mock *MockInt64ObservableCounter
}

// NewMockInt64ObservableCounter creates a new mock instance.
func NewMockInt64ObservableCounter(ctrl *gomock.Controller) *MockInt64ObservableCounter {
	mock := &MockInt64ObservableCounter{ctrl: ctrl}
	mock.recorder = &MockInt64ObservableCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64ObservableCounter) EXPECT() *MockInt64ObservableCounterMockRecorder {
	return m.recorder
}

// int64Observable mocks base method.
func (m *MockInt64ObservableCounter) int64Observable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64Observable")
}

// int64Observable indicates an expected call of int64Observable.
func (mr *MockInt64ObservableCounterMockRecorder) int64Observable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64Observable", reflect.TypeOf((*MockInt64ObservableCounter)(nil).int64Observable))
}

// int64ObservableCounter mocks base method.
func (m *MockInt64ObservableCounter) int64ObservableCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64ObservableCounter")
}

// int64ObservableCounter indicates an expected call of int64ObservableCounter.
func (mr *MockInt64ObservableCounterMockRecorder) int64ObservableCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64ObservableCounter", reflect.TypeOf((*MockInt64ObservableCounter)(nil).int64ObservableCounter))
}

// observable mocks base method.
func (m *MockInt64ObservableCounter) observable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "observable")
}

// observable indicates an expected call of observable.
func (mr *MockInt64ObservableCounterMockRecorder) observable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "observable", reflect.TypeOf((*MockInt64ObservableCounter)(nil).observable))
}
