// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Int64Observer)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/asyncint64observer.go -package otelmock go.opentelemetry.io/otel/metric Int64Observer
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockInt64Observer is a mock of Int64Observer interface.
type MockInt64Observer struct {
	metric.Int64Observer

	ctrl     *gomock.Controller
	recorder *MockInt64ObserverMockRecorder
	isgomock struct{}
}

// MockInt64ObserverMockRecorder is the mock recorder for MockInt64Observer.
type MockInt64ObserverMockRecorder struct {
	mock *MockInt64Observer
}

// NewMockInt64Observer creates a new mock instance.
func NewMockInt64Observer(ctrl *gomock.Controller) *MockInt64Observer {
	mock := &MockInt64Observer{ctrl: ctrl}
	mock.recorder = &MockInt64ObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64Observer) EXPECT() *MockInt64ObserverMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockInt64Observer) Observe(value int64, options ...metric.ObserveOption) {
	m.ctrl.T.Helper()
	varargs := []any{value}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Observe", varargs...)
}

// Observe indicates an expected call of Observe.
func (mr *MockInt64ObserverMockRecorder) Observe(value any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{value}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockInt64Observer)(nil).Observe), varargs...)
}

// int64Observer mocks base method.
func (m *MockInt64Observer) int64Observer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64Observer")
}

// int64Observer indicates an expected call of int64Observer.
func (mr *MockInt64ObserverMockRecorder) int64Observer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64Observer", reflect.TypeOf((*MockInt64Observer)(nil).int64Observer))
}
