// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Float64Observer)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/asyncfloat64observer.go -package otelmock go.opentelemetry.io/otel/metric Float64Observer
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockFloat64Observer is a mock of Float64Observer interface.
type MockFloat64Observer struct {
	metric.Float64Observer

	ctrl     *gomock.Controller
	recorder *MockFloat64ObserverMockRecorder
	isgomock struct{}
}

// MockFloat64ObserverMockRecorder is the mock recorder for MockFloat64Observer.
type MockFloat64ObserverMockRecorder struct {
	mock *MockFloat64Observer
}

// NewMockFloat64Observer creates a new mock instance.
func NewMockFloat64Observer(ctrl *gomock.Controller) *MockFloat64Observer {
	mock := &MockFloat64Observer{ctrl: ctrl}
	mock.recorder = &MockFloat64ObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFloat64Observer) EXPECT() *MockFloat64ObserverMockRecorder {
	return m.recorder
}

// Observe mocks base method.
func (m *MockFloat64Observer) Observe(value float64, options ...metric.ObserveOption) {
	m.ctrl.T.Helper()
	varargs := []any{value}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Observe", varargs...)
}

// Observe indicates an expected call of Observe.
func (mr *MockFloat64ObserverMockRecorder) Observe(value any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{value}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockFloat64Observer)(nil).Observe), varargs...)
}

// float64Observer mocks base method.
func (m *MockFloat64Observer) float64Observer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "float64Observer")
}

// float64Observer indicates an expected call of float64Observer.
func (mr *MockFloat64ObserverMockRecorder) float64Observer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "float64Observer", reflect.TypeOf((*MockFloat64Observer)(nil).float64Observer))
}
