// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/sdk/metric (interfaces: Exporter)

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/sdk/metric"
	metricdata "go.opentelemetry.io/otel/sdk/metric/metricdata"
	gomock "go.uber.org/mock/gomock"
)

// MockExporter is a mock of Exporter interface.
type MockExporter struct {
	metric.Exporter

	ctrl     *gomock.Controller
	recorder *MockExporterMockRecorder
	isgomock struct{}
}

// MockExporterMockRecorder is the mock recorder for MockExporter.
type MockExporterMockRecorder struct {
	mock *MockExporter
}

// NewMockExporter creates a new mock instance.
func NewMockExporter(ctrl *gomock.Controller) *MockExporter {
	mock := &MockExporter{ctrl: ctrl}
	mock.recorder = &MockExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExporter) EXPECT() *MockExporterMockRecorder {
	return m.recorder
}

// Aggregation mocks base method.
func (m *MockExporter) Aggregation(arg0 metric.InstrumentKind) metric.Aggregation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregation", arg0)
	ret0, _ := ret[0].(metric.Aggregation)
	return ret0
}

// Aggregation indicates an expected call of Aggregation.
func (mr *MockExporterMockRecorder) Aggregation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregation", reflect.TypeOf((*MockExporter)(nil).Aggregation), arg0)
}

// Export mocks base method.
func (m *MockExporter) Export(arg0 context.Context, arg1 *metricdata.ResourceMetrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockExporterMockRecorder) Export(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockExporter)(nil).Export), arg0, arg1)
}

// ForceFlush mocks base method.
func (m *MockExporter) ForceFlush(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceFlush", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceFlush indicates an expected call of ForceFlush.
func (mr *MockExporterMockRecorder) ForceFlush(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceFlush", reflect.TypeOf((*MockExporter)(nil).ForceFlush), arg0)
}

// Shutdown mocks base method.
func (m *MockExporter) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockExporterMockRecorder) Shutdown(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockExporter)(nil).Shutdown), arg0)
}

// Temporality mocks base method.
func (m *MockExporter) Temporality(arg0 metric.InstrumentKind) metricdata.Temporality {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Temporality", arg0)
	ret0, _ := ret[0].(metricdata.Temporality)
	return ret0
}

// Temporality indicates an expected call of Temporality.
func (mr *MockExporterMockRecorder) Temporality(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Temporality", reflect.TypeOf((*MockExporter)(nil).Temporality), arg0)
}
