// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Float64Gauge)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/float64gauge.go -package otelmock go.opentelemetry.io/otel/metric Float64Gauge
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockFloat64Gauge is a mock of Float64Gauge interface.
type MockFloat64Gauge struct {
	metric.Float64Gauge

	ctrl     *gomock.Controller
	recorder *MockFloat64GaugeMockRecorder
	isgomock struct{}
}

// MockFloat64GaugeMockRecorder is the mock recorder for MockFloat64Gauge.
type MockFloat64GaugeMockRecorder struct {
	mock *MockFloat64Gauge
}

// NewMockFloat64Gauge creates a new mock instance.
func NewMockFloat64Gauge(ctrl *gomock.Controller) *MockFloat64Gauge {
	mock := &MockFloat64Gauge{ctrl: ctrl}
	mock.recorder = &MockFloat64GaugeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFloat64Gauge) EXPECT() *MockFloat64GaugeMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockFloat64Gauge) Enabled(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockFloat64GaugeMockRecorder) Enabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockFloat64Gauge)(nil).Enabled), arg0)
}

// Record mocks base method.
func (m *MockFloat64Gauge) Record(ctx context.Context, value float64, options ...metric.RecordOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, value}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Record", varargs...)
}

// Record indicates an expected call of Record.
func (mr *MockFloat64GaugeMockRecorder) Record(ctx, value any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, value}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockFloat64Gauge)(nil).Record), varargs...)
}

// float64Gauge mocks base method.
func (m *MockFloat64Gauge) float64Gauge() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "float64Gauge")
}

// float64Gauge indicates an expected call of float64Gauge.
func (mr *MockFloat64GaugeMockRecorder) float64Gauge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "float64Gauge", reflect.TypeOf((*MockFloat64Gauge)(nil).float64Gauge))
}
