// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Float64UpDownCounter)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/float64updowncounter.go -package otelmock go.opentelemetry.io/otel/metric Float64UpDownCounter
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockFloat64UpDownCounter is a mock of Float64UpDownCounter interface.
type MockFloat64UpDownCounter struct {
	metric.Float64UpDownCounter

	ctrl     *gomock.Controller
	recorder *MockFloat64UpDownCounterMockRecorder
	isgomock struct{}
}

// MockFloat64UpDownCounterMockRecorder is the mock recorder for MockFloat64UpDownCounter.
type MockFloat64UpDownCounterMockRecorder struct {
	mock *MockFloat64UpDownCounter
}

// NewMockFloat64UpDownCounter creates a new mock instance.
func NewMockFloat64UpDownCounter(ctrl *gomock.Controller) *MockFloat64UpDownCounter {
	mock := &MockFloat64UpDownCounter{ctrl: ctrl}
	mock.recorder = &MockFloat64UpDownCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFloat64UpDownCounter) EXPECT() *MockFloat64UpDownCounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFloat64UpDownCounter) Add(ctx context.Context, incr float64, options ...metric.AddOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, incr}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Add", varargs...)
}

// Add indicates an expected call of Add.
func (mr *MockFloat64UpDownCounterMockRecorder) Add(ctx, incr any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, incr}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFloat64UpDownCounter)(nil).Add), varargs...)
}

// Enabled mocks base method.
func (m *MockFloat64UpDownCounter) Enabled(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockFloat64UpDownCounterMockRecorder) Enabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockFloat64UpDownCounter)(nil).Enabled), arg0)
}

// float64UpDownCounter mocks base method.
func (m *MockFloat64UpDownCounter) float64UpDownCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "float64UpDownCounter")
}

// float64UpDownCounter indicates an expected call of float64UpDownCounter.
func (mr *MockFloat64UpDownCounterMockRecorder) float64UpDownCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "float64UpDownCounter", reflect.TypeOf((*MockFloat64UpDownCounter)(nil).float64UpDownCounter))
}
