// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Float64Counter)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/float64counter.go -package otelmock go.opentelemetry.io/otel/metric Float64Counter
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockFloat64Counter is a mock of Float64Counter interface.
type MockFloat64Counter struct {
	metric.Float64Counter

	ctrl     *gomock.Controller
	recorder *MockFloat64CounterMockRecorder
	isgomock struct{}
}

// MockFloat64CounterMockRecorder is the mock recorder for MockFloat64Counter.
type MockFloat64CounterMockRecorder struct {
	mock *MockFloat64Counter
}

// NewMockFloat64Counter creates a new mock instance.
func NewMockFloat64Counter(ctrl *gomock.Controller) *MockFloat64Counter {
	mock := &MockFloat64Counter{ctrl: ctrl}
	mock.recorder = &MockFloat64CounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFloat64Counter) EXPECT() *MockFloat64CounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFloat64Counter) Add(ctx context.Context, incr float64, options ...metric.AddOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, incr}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Add", varargs...)
}

// Add indicates an expected call of Add.
func (mr *MockFloat64CounterMockRecorder) Add(ctx, incr any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, incr}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFloat64Counter)(nil).Add), varargs...)
}

// Enabled mocks base method.
func (m *MockFloat64Counter) Enabled(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockFloat64CounterMockRecorder) Enabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockFloat64Counter)(nil).Enabled), arg0)
}

// float64Counter mocks base method.
func (m *MockFloat64Counter) float64Counter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "float64Counter")
}

// float64Counter indicates an expected call of float64Counter.
func (mr *MockFloat64CounterMockRecorder) float64Counter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "float64Counter", reflect.TypeOf((*MockFloat64Counter)(nil).float64Counter))
}
