// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Int64Gauge)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/int64gauge.go -package otelmock go.opentelemetry.io/otel/metric Int64Gauge
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockInt64Gauge is a mock of Int64Gauge interface.
type MockInt64Gauge struct {
	metric.Int64Gauge

	ctrl     *gomock.Controller
	recorder *MockInt64GaugeMockRecorder
	isgomock struct{}
}

// MockInt64GaugeMockRecorder is the mock recorder for MockInt64Gauge.
type MockInt64GaugeMockRecorder struct {
	mock *MockInt64Gauge
}

// NewMockInt64Gauge creates a new mock instance.
func NewMockInt64Gauge(ctrl *gomock.Controller) *MockInt64Gauge {
	mock := &MockInt64Gauge{ctrl: ctrl}
	mock.recorder = &MockInt64GaugeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64Gauge) EXPECT() *MockInt64GaugeMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockInt64Gauge) Enabled(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockInt64GaugeMockRecorder) Enabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockInt64Gauge)(nil).Enabled), arg0)
}

// Record mocks base method.
func (m *MockInt64Gauge) Record(ctx context.Context, value int64, options ...metric.RecordOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, value}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Record", varargs...)
}

// Record indicates an expected call of Record.
func (mr *MockInt64GaugeMockRecorder) Record(ctx, value any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, value}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockInt64Gauge)(nil).Record), varargs...)
}

// int64Gauge mocks base method.
func (m *MockInt64Gauge) int64Gauge() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64Gauge")
}

// int64Gauge indicates an expected call of int64Gauge.
func (mr *MockInt64GaugeMockRecorder) int64Gauge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64Gauge", reflect.TypeOf((*MockInt64Gauge)(nil).int64Gauge))
}
