// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Int64Histogram)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/int64histogram.go -package otelmock go.opentelemetry.io/otel/metric Int64Histogram
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockInt64Histogram is a mock of Int64Histogram interface.
type MockInt64Histogram struct {
	metric.Int64Histogram

	ctrl     *gomock.Controller
	recorder *MockInt64HistogramMockRecorder
	isgomock struct{}
}

// MockInt64HistogramMockRecorder is the mock recorder for MockInt64Histogram.
type MockInt64HistogramMockRecorder struct {
	mock *MockInt64Histogram
}

// NewMockInt64Histogram creates a new mock instance.
func NewMockInt64Histogram(ctrl *gomock.Controller) *MockInt64Histogram {
	mock := &MockInt64Histogram{ctrl: ctrl}
	mock.recorder = &MockInt64HistogramMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64Histogram) EXPECT() *MockInt64HistogramMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockInt64Histogram) Enabled(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockInt64HistogramMockRecorder) Enabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockInt64Histogram)(nil).Enabled), arg0)
}

// Record mocks base method.
func (m *MockInt64Histogram) Record(ctx context.Context, incr int64, options ...metric.RecordOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, incr}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Record", varargs...)
}

// Record indicates an expected call of Record.
func (mr *MockInt64HistogramMockRecorder) Record(ctx, incr any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, incr}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockInt64Histogram)(nil).Record), varargs...)
}

// int64Histogram mocks base method.
func (m *MockInt64Histogram) int64Histogram() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64Histogram")
}

// int64Histogram indicates an expected call of int64Histogram.
func (mr *MockInt64HistogramMockRecorder) int64Histogram() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64Histogram", reflect.TypeOf((*MockInt64Histogram)(nil).int64Histogram))
}
