// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Int64UpDownCounter)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/int64updowncounter.go -package otelmock go.opentelemetry.io/otel/metric Int64UpDownCounter
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockInt64UpDownCounter is a mock of Int64UpDownCounter interface.
type MockInt64UpDownCounter struct {
	metric.Int64UpDownCounter

	ctrl     *gomock.Controller
	recorder *MockInt64UpDownCounterMockRecorder
	isgomock struct{}
}

// MockInt64UpDownCounterMockRecorder is the mock recorder for MockInt64UpDownCounter.
type MockInt64UpDownCounterMockRecorder struct {
	mock *MockInt64UpDownCounter
}

// NewMockInt64UpDownCounter creates a new mock instance.
func NewMockInt64UpDownCounter(ctrl *gomock.Controller) *MockInt64UpDownCounter {
	mock := &MockInt64UpDownCounter{ctrl: ctrl}
	mock.recorder = &MockInt64UpDownCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64UpDownCounter) EXPECT() *MockInt64UpDownCounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockInt64UpDownCounter) Add(ctx context.Context, incr int64, options ...metric.AddOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, incr}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Add", varargs...)
}

// Add indicates an expected call of Add.
func (mr *MockInt64UpDownCounterMockRecorder) Add(ctx, incr any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, incr}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockInt64UpDownCounter)(nil).Add), varargs...)
}

// Enabled mocks base method.
func (m *MockInt64UpDownCounter) Enabled(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockInt64UpDownCounterMockRecorder) Enabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockInt64UpDownCounter)(nil).Enabled), arg0)
}

// int64UpDownCounter mocks base method.
func (m *MockInt64UpDownCounter) int64UpDownCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64UpDownCounter")
}

// int64UpDownCounter indicates an expected call of int64UpDownCounter.
func (mr *MockInt64UpDownCounterMockRecorder) int64UpDownCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64UpDownCounter", reflect.TypeOf((*MockInt64UpDownCounter)(nil).int64UpDownCounter))
}
