// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Int64Histogram)

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	metric "go.opentelemetry.io/otel/metric"
)

// MockInt64Histogram is a mock of Int64Histogram interface.
type MockInt64Histogram struct {
	ctrl     *gomock.Controller
	recorder *MockInt64HistogramMockRecorder
}

// MockInt64HistogramMockRecorder is the mock recorder for MockInt64Histogram.
type MockInt64HistogramMockRecorder struct {
	mock *MockInt64Histogram
}

// NewMockInt64Histogram creates a new mock instance.
func NewMockInt64Histogram(ctrl *gomock.Controller) *MockInt64Histogram {
	mock := &MockInt64Histogram{ctrl: ctrl}
	mock.recorder = &MockInt64HistogramMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64Histogram) EXPECT() *MockInt64HistogramMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockInt64Histogram) Record(arg0 context.Context, arg1 int64, arg2 ...metric.RecordOption) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Record", varargs...)
}

// Record indicates an expected call of Record.
func (mr *MockInt64HistogramMockRecorder) Record(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockInt64Histogram)(nil).Record), varargs...)
}

// int64Histogram mocks base method.
func (m *MockInt64Histogram) int64Histogram() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64Histogram")
}

// int64Histogram indicates an expected call of int64Histogram.
func (mr *MockInt64HistogramMockRecorder) int64Histogram() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64Histogram", reflect.TypeOf((*MockInt64Histogram)(nil).int64Histogram))
}
