// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Int64Counter)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/int64counter.go -package otelmock go.opentelemetry.io/otel/metric Int64Counter
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockInt64Counter is a mock of Int64Counter interface.
type MockInt64Counter struct {
	metric.Int64Counter

	ctrl     *gomock.Controller
	recorder *MockInt64CounterMockRecorder
	isgomock struct{}
}

// MockInt64CounterMockRecorder is the mock recorder for MockInt64Counter.
type MockInt64CounterMockRecorder struct {
	mock *MockInt64Counter
}

// NewMockInt64Counter creates a new mock instance.
func NewMockInt64Counter(ctrl *gomock.Controller) *MockInt64Counter {
	mock := &MockInt64Counter{ctrl: ctrl}
	mock.recorder = &MockInt64CounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64Counter) EXPECT() *MockInt64CounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockInt64Counter) Add(ctx context.Context, incr int64, options ...metric.AddOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, incr}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Add", varargs...)
}

// Add indicates an expected call of Add.
func (mr *MockInt64CounterMockRecorder) Add(ctx, incr any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, incr}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockInt64Counter)(nil).Add), varargs...)
}

// Enabled mocks base method.
func (m *MockInt64Counter) Enabled(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockInt64CounterMockRecorder) Enabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockInt64Counter)(nil).Enabled), arg0)
}

// int64Counter mocks base method.
func (m *MockInt64Counter) int64Counter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "int64Counter")
}

// int64Counter indicates an expected call of int64Counter.
func (mr *MockInt64CounterMockRecorder) int64Counter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "int64Counter", reflect.TypeOf((*MockInt64Counter)(nil).int64Counter))
}
