// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: MeterProvider)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/meter_provider.go -package otelmock go.opentelemetry.io/otel/metric MeterProvider
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockMeterProvider is a mock of MeterProvider interface.
type MockMeterProvider struct {
	metric.MeterProvider

	ctrl     *gomock.Controller
	recorder *MockMeterProviderMockRecorder
	isgomock struct{}
}

// MockMeterProviderMockRecorder is the mock recorder for MockMeterProvider.
type MockMeterProviderMockRecorder struct {
	mock *MockMeterProvider
}

// NewMockMeterProvider creates a new mock instance.
func NewMockMeterProvider(ctrl *gomock.Controller) *MockMeterProvider {
	mock := &MockMeterProvider{ctrl: ctrl}
	mock.recorder = &MockMeterProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeterProvider) EXPECT() *MockMeterProviderMockRecorder {
	return m.recorder
}

// Meter mocks base method.
func (m *MockMeterProvider) Meter(name string, opts ...metric.MeterOption) metric.Meter {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Meter", varargs...)
	ret0, _ := ret[0].(metric.Meter)
	return ret0
}

// Meter indicates an expected call of Meter.
func (mr *MockMeterProviderMockRecorder) Meter(name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Meter", reflect.TypeOf((*MockMeterProvider)(nil).Meter), varargs...)
}

// meterProvider mocks base method.
func (m *MockMeterProvider) meterProvider() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "meterProvider")
}

// meterProvider indicates an expected call of meterProvider.
func (mr *MockMeterProviderMockRecorder) meterProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "meterProvider", reflect.TypeOf((*MockMeterProvider)(nil).meterProvider))
}
