// Code generated by MockGen. DO NOT EDIT.
// Source: go.opentelemetry.io/otel/metric (interfaces: Observer)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/etienne/Documents/Scalingo/golang/src/github.com/Scalingo/go-utils/otel/otelmock/observer.go -package otelmock go.opentelemetry.io/otel/metric Observer
//

// Package otelmock is a generated GoMock package.
package otelmock

import (
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	metric.Observer

	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// ObserveFloat64 mocks base method.
func (m *MockObserver) ObserveFloat64(obsrv metric.Float64Observable, value float64, opts ...metric.ObserveOption) {
	m.ctrl.T.Helper()
	varargs := []any{obsrv, value}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ObserveFloat64", varargs...)
}

// ObserveFloat64 indicates an expected call of ObserveFloat64.
func (mr *MockObserverMockRecorder) ObserveFloat64(obsrv, value any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{obsrv, value}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveFloat64", reflect.TypeOf((*MockObserver)(nil).ObserveFloat64), varargs...)
}

// ObserveInt64 mocks base method.
func (m *MockObserver) ObserveInt64(obsrv metric.Int64Observable, value int64, opts ...metric.ObserveOption) {
	m.ctrl.T.Helper()
	varargs := []any{obsrv, value}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ObserveInt64", varargs...)
}

// ObserveInt64 indicates an expected call of ObserveInt64.
func (mr *MockObserverMockRecorder) ObserveInt64(obsrv, value any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{obsrv, value}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveInt64", reflect.TypeOf((*MockObserver)(nil).ObserveInt64), varargs...)
}

// observer mocks base method.
func (m *MockObserver) observer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "observer")
}

// observer indicates an expected call of observer.
func (mr *MockObserverMockRecorder) observer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "observer", reflect.TypeOf((*MockObserver)(nil).observer))
}
